# Copyright 2020 the V8 project authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: Update API documentation

on:
  push:
    branches:
      - main
  schedule:
    # Rebuild docs every day at 3am.
    - cron: '0 3 * * *'

jobs:
  build:
    name: Build and update docs
    runs-on: ubuntu-latest
    container:
      image: docker://python:3.7-alpine
    steps:
      - name: Install dependencies
        run: |
          apk add doxygen git graphviz openssh-client rsync tar ttf-freefont zstd
      - name: Checkout API repo
        uses: actions/checkout@v2
      - name: Restore cached doc SHAs
        uses: actions/cache@v2
        with:
          path: dist/*/.sha
          key: dist-${{ hashFiles('dist/*/.sha') }}
          restore-keys: |
            dist-
      - name: Build docs
        run: |
          python update.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: dist
          GIT_CONFIG_NAME: V8 API docs updater
          GIT_CONFIG_EMAIL: v8-dev+api@googlegroups.com
